import { TopicFact, TopicFacts } from '../types/fact';
import React from 'react';
import {
  Sun,
  TreePine,
  DollarSign,
  HeartPulse,
  Shield,
  GraduationCap,
  Users,
  Lock,
  Building2,
  Globe,
  Wallet,
  Scale,
  Stethoscope,
  Pill,
  Radar,
  School,
  FileCheck,
  ShieldAlert,
  Cpu,
  KeyRound,
  Network,
  Construction,
  Router,
  Briefcase,
  BarChart,
  Wind,
  Zap,
  Flame,
  Plane
} from 'lucide-react';
import { createIcon } from '../utils/iconUtils';

const topicFactsData: Record<string, TopicFact[]> = {
  'Climate Change and Environmental Policy': [
    {
      icon: createIcon(Sun, "#FFA500"),
      title: "Solar Energy Growth",
      content: "Solar energy costs have dropped 89% in the past decade",
      emotional: "Clean energy is becoming more affordable than ever",
      color: "bg-orange-50",
      textColor: "text-orange-800",
    },
    {
      icon: createIcon(TreePine, "#22C55E"),
      title: "Deforestation Impact",
      content: "15 billion trees are cut down each year globally",
      emotional: "Our planet loses vital carbon capture capacity daily",
      color: "bg-green-50",
      textColor: "text-green-800",
    },
    {
      icon: createIcon(Wind, "#60A5FA"),
      title: "Rising Temperatures",
      content: "Global temperature has risen 1.1°C since pre-industrial times",
      emotional: "Every fraction of a degree impacts millions of lives",
      color: "bg-blue-50",
      textColor: "text-blue-800",
    },
    {
      icon: createIcon(Zap, "#EAB308"),
      title: "Renewable Transition",
      content: "Renewable energy now accounts for 29% of global electricity",
      emotional: "The clean energy revolution is gaining momentum",
      color: "bg-yellow-50",
      textColor: "text-yellow-800",
    },
    {
      icon: createIcon(Flame, "#EF4444"),
      title: "Carbon Emissions",
      content: "Current CO2 levels are highest in 2 million years",
      emotional: "We're in uncharted territory for Earth's climate",
      color: "bg-red-50",
      textColor: "text-red-800",
    }
  ],
  'Economic Inequality and Wealth Distribution': [
    {
      icon: createIcon(DollarSign, "#22C55E"),
      title: "Wealth Gap",
      content: "The richest 1% own 45% of global wealth",
      emotional: "Economic disparity reaches historic levels",
      color: "bg-green-50",
      textColor: "text-green-800",
    },
    {
      icon: createIcon(Wallet, "#6366F1"),
      title: "Income Stagnation",
      content: "Middle-class wages have grown only 6% since 1979",
      emotional: "Decades of minimal progress for working families",
      color: "bg-indigo-50",
      textColor: "text-indigo-800",
    },
    {
      icon: createIcon(Building2, "#8B5CF6"),
      title: "Corporate Profits",
      content: "Corporate profits at 70-year high while wages decline",
      emotional: "The disconnect between profits and wages widens",
      color: "bg-purple-50",
      textColor: "text-purple-800",
    },
    {
      icon: createIcon(BarChart, "#EC4899"),
      title: "Social Mobility",
      content: "93% born in bottom quintile never reach top quintile",
      emotional: "The American Dream becomes increasingly elusive",
      color: "bg-pink-50",
      textColor: "text-pink-800",
    },
    {
      icon: createIcon(Globe, "#14B8A6"),
      title: "Global Impact",
      content: "3.4 billion people live on less than $5.50 per day",
      emotional: "Half the world struggles for basic necessities",
      color: "bg-teal-50",
      textColor: "text-teal-800",
    }
  ],
  'Healthcare System Reform': [
    {
      icon: createIcon(HeartPulse, "#EF4444"),
      title: "Access Crisis",
      content: "28.9 million Americans remain uninsured",
      emotional: "Millions face impossible healthcare choices daily",
      color: "bg-red-50",
      textColor: "text-red-800",
    },
    {
      icon: createIcon(Stethoscope, "#8B5CF6"),
      title: "Cost Burden",
      content: "Medical debt affects 100 million Americans",
      emotional: "Healthcare costs push families into poverty",
      color: "bg-purple-50",
      textColor: "text-purple-800",
    },
    {
      icon: createIcon(Pill, "#EC4899"),
      title: "Drug Pricing",
      content: "Prescription drug prices 2.56 times higher than other nations",
      emotional: "Life-saving medications remain out of reach for many",
      color: "bg-pink-50",
      textColor: "text-pink-800",
    },
    {
      icon: createIcon(Shield, "#14B8A6"),
      title: "Prevention Gap",
      content: "Only 8% of US healthcare spending goes to prevention",
      emotional: "We treat illness instead of promoting wellness",
      color: "bg-teal-50",
      textColor: "text-teal-800",
    },
    {
      icon: createIcon(Users, "#6366F1"),
      title: "Provider Shortage",
      content: "US faces shortage of 124,000 physicians by 2034",
      emotional: "Healthcare system strains under growing demand",
      color: "bg-indigo-50",
      textColor: "text-indigo-800",
    }
  ],
  'National Security and Defense': [
    {
      icon: createIcon(Shield, "#DC2626"),
      title: "Cyber Threats",
      content: "Cyberattacks increased 38% globally in 2022",
      emotional: "Digital warfare becomes the new battlefront",
      color: "bg-red-50",
      textColor: "text-red-800",
    },
    {
      icon: createIcon(Lock, "#4F46E5"),
      title: "Infrastructure Security",
      content: "55% of critical infrastructure vulnerable to attacks",
      emotional: "Our nation's foundations need stronger protection",
      color: "bg-indigo-50",
      textColor: "text-indigo-800",
    },
    {
      icon: createIcon(Radar, "#0EA5E9"),
      title: "Defense Readiness",
      content: "Military readiness at lowest level in 15 years",
      emotional: "Traditional defense faces modern challenges",
      color: "bg-sky-50",
      textColor: "text-sky-800",
    },
    {
      icon: createIcon(ShieldAlert, "#EAB308"),
      title: "Emerging Threats",
      content: "AI weapons development accelerates globally",
      emotional: "Technology reshapes the nature of conflict",
      color: "bg-yellow-50",
      textColor: "text-yellow-800",
    },
    {
      icon: createIcon(Globe, "#22C55E"),
      title: "Alliance Dynamics",
      content: "NATO defense spending up 8.3% in 2023",
      emotional: "Global partnerships crucial for security",
      color: "bg-green-50",
      textColor: "text-green-800",
    }
  ],
  'Education System Reform': [
    {
      icon: createIcon(GraduationCap, "#6366F1"),
      title: "Student Debt Crisis",
      content: "44.7 million Americans owe $1.7 trillion in student loans",
      emotional: "Education dreams weighted by financial burden",
      color: "bg-indigo-50",
      textColor: "text-indigo-800",
    },
    {
      icon: createIcon(School, "#EC4899"),
      title: "Achievement Gap",
      content: "13-point reading gap between high and low-income students",
      emotional: "Opportunity divide starts in early education",
      color: "bg-pink-50",
      textColor: "text-pink-800",
    },
    {
      icon: createIcon(Users, "#14B8A6"),
      title: "Teacher Shortage",
      content: "36% of schools report teaching vacancies",
      emotional: "Educators stretched thin across America",
      color: "bg-teal-50",
      textColor: "text-teal-800",
    },
    {
      icon: createIcon(Network, "#8B5CF6"),
      title: "Digital Divide",
      content: "9 million students lack home internet access",
      emotional: "Technology gap widens educational inequity",
      color: "bg-purple-50",
      textColor: "text-purple-800",
    },
    {
      icon: createIcon(FileCheck, "#EF4444"),
      title: "Curriculum Reform",
      content: "Only 37% of students are college-ready in core subjects",
      emotional: "Education system struggles to prepare future leaders",
      color: "bg-red-50",
      textColor: "text-red-800",
    }
  ],
  'Immigration Policy': [
    {
      icon: createIcon(Plane, "#4F46E5"),
      title: "Visa Backlog",
      content: "9 million visa applications pending worldwide",
      emotional: "Families separated by bureaucratic delays",
      color: "bg-indigo-50",
      textColor: "text-indigo-800",
    },
    {
      icon: createIcon(Globe, "#EC4899"),
      title: "Economic Impact",
      content: "Immigrants contribute $2 trillion to US GDP annually",
      emotional: "Immigration drives economic growth and innovation",
      color: "bg-pink-50",
      textColor: "text-pink-800",
    },
    {
      icon: createIcon(Users, "#22C55E"),
      title: "Labor Force",
      content: "Immigrants fill 47% of science and engineering jobs",
      emotional: "Talent knows no borders",
      color: "bg-green-50",
      textColor: "text-green-800",
    },
    {
      icon: createIcon(Scale, "#8B5CF6"),
      title: "Legal System",
      content: "Immigration court backlog exceeds 1.6 million cases",
      emotional: "Justice delayed is justice denied",
      color: "bg-purple-50",
      textColor: "text-purple-800",
    },
    {
      icon: createIcon(Shield, "#EF4444"),
      title: "Border Security",
      content: "$18 billion spent annually on border enforcement",
      emotional: "Balancing security with humanity",
      color: "bg-red-50",
      textColor: "text-red-800",
    }
  ],
  'Technology Regulation and Privacy': [
    {
      icon: createIcon(Lock, "#EF4444"),
      title: "Data Breaches",
      content: "4.1 billion records exposed in first half of 2023",
      emotional: "Personal privacy increasingly vulnerable",
      color: "bg-red-50",
      textColor: "text-red-800",
    },
    {
      icon: createIcon(Cpu, "#6366F1"),
      title: "AI Regulation",
      content: "AI market to reach $190 billion by 2025",
      emotional: "Technology outpaces regulatory frameworks",
      color: "bg-indigo-50",
      textColor: "text-indigo-800",
    },
    {
      icon: createIcon(KeyRound, "#8B5CF6"),
      title: "Privacy Rights",
      content: "87% of Americans consider data privacy a human right",
      emotional: "Digital rights become civil rights",
      color: "bg-purple-50",
      textColor: "text-purple-800",
    },
    {
      icon: createIcon(Shield, "#14B8A6"),
      title: "Tech Monopolies",
      content: "5 tech companies control 95% of digital advertising",
      emotional: "Power concentration threatens innovation",
      color: "bg-teal-50",
      textColor: "text-teal-800",
    },
    {
      icon: createIcon(Network, "#EC4899"),
      title: "Digital Divide",
      content: "19 million Americans lack broadband access",
      emotional: "Technology access determines opportunity",
      color: "bg-pink-50",
      textColor: "text-pink-800",
    }
  ],
  'Infrastructure Development': [
    {
      icon: createIcon(Construction, "#22C55E"),
      title: "Aging Systems",
      content: "42% of bridges are at least 50 years old",
      emotional: "America's foundation shows its age",
      color: "bg-green-50",
      textColor: "text-green-800",
    },
    {
      icon: createIcon(Router, "#6366F1"),
      title: "Digital Infrastructure",
      content: "US ranks 13th globally in internet speed",
      emotional: "Digital future requires modern backbone",
      color: "bg-indigo-50",
      textColor: "text-indigo-800",
    },
    {
      icon: createIcon(Zap, "#EF4444"),
      title: "Power Grid",
      content: "Power outages up 67% since 2000",
      emotional: "Reliability of basics becomes uncertain",
      color: "bg-red-50",
      textColor: "text-red-800",
    },
    {
      icon: createIcon(Globe, "#8B5CF6"),
      title: "Transportation",
      content: "$786 billion backlog in highway and bridge capital needs",
      emotional: "Movement of people and goods at risk",
      color: "bg-purple-50",
      textColor: "text-purple-800",
    },
    {
      icon: createIcon(Building2, "#14B8A6"),
      title: "Urban Development",
      content: "68% of US population will live in cities by 2050",
      emotional: "Cities struggle to keep pace with growth",
      color: "bg-teal-50",
      textColor: "text-teal-800",
    }
  ],
  'International Trade Relations': [
    {
      icon: createIcon(Globe, "#22C55E"),
      title: "Trade Deficit",
      content: "US trade deficit reached $948.1 billion in 2022",
      emotional: "Global commerce balance shifts",
      color: "bg-green-50",
      textColor: "text-green-800",
    },
    {
      icon: createIcon(Briefcase, "#6366F1"),
      title: "Supply Chains",
      content: "75% of companies report supply chain disruptions",
      emotional: "Interconnected world shows vulnerability",
      color: "bg-indigo-50",
      textColor: "text-indigo-800",
    },
    {
      icon: createIcon(Scale, "#EF4444"),
      title: "Tariff Impact",
      content: "Average US household pays $831 annually in tariffs",
      emotional: "Trade policies affect everyday lives",
      color: "bg-red-50",
      textColor: "text-red-800",
    },
    {
      icon: createIcon(DollarSign, "#8B5CF6"),
      title: "Currency Relations",
      content: "Dollar represents 59% of global reserves",
      emotional: "Financial power shapes global relations",
      color: "bg-purple-50",
      textColor: "text-purple-800",
    },
    {
      icon: createIcon(BarChart, "#14B8A6"),
      title: "Trade Agreements",
      content: "US has free trade agreements with 20 countries",
      emotional: "Partnerships define economic future",
      color: "bg-teal-50",
      textColor: "text-teal-800",
    }
  ],
  'Energy Policy and Renewable Resources': [
    {
      icon: createIcon(Zap, "#EAB308"),
      title: "Grid Transformation",
      content: "Renewable energy now 20% of utility-scale generation",
      emotional: "Clean energy revolution gains momentum",
      color: "bg-yellow-50",
      textColor: "text-yellow-800",
    },
    {
      icon: createIcon(Sun, "#22C55E"),
      title: "Solar Growth",
      content: "Solar installations increased 43% year-over-year",
      emotional: "Sun powers our sustainable future",
      color: "bg-green-50",
      textColor: "text-green-800",
    },
    {
      icon: createIcon(Wind, "#6366F1"),
      title: "Wind Energy",
      content: "Wind power costs decreased 70% since 2009",
      emotional: "Nature provides affordable solutions",
      color: "bg-indigo-50",
      textColor: "text-indigo-800",
    },
    {
      icon: createIcon(Flame, "#EF4444"),
      title: "Fossil Transition",
      content: "50% of US coal plants announced retirement",
      emotional: "Era of fossil fuels begins to sunset",
      color: "bg-red-50",
      textColor: "text-red-800",
    },
    {
      icon: createIcon(Building2, "#8B5CF6"),
      title: "Infrastructure Need",
      content: "$360 billion needed for grid modernization",
      emotional: "Investment in future powers progress",
      color: "bg-purple-50",
      textColor: "text-purple-800",
    }
  ]
};

export function getTopicFacts(topicId: number, topicTitle: string): TopicFacts {
  return {
    topicId,
    facts: topicFactsData[topicTitle] || [],
  };
}


// Test
console.log(getTopicFacts(0, "Climate Change and Environmental Policy"));